import type { Product } from "../types/Product";

export const products: Product[] = [
  {
    id: 1,
    name: "Nike 24.7 PerfectStretch",
    category: "Men's Dri-FIT Short-Sleeve Button-Down Top",
    price: 85,
    description:
      "Made for all-day comfort, our PerfectStretch fabric has four-way stretch and a polished look. This button-down top puts it to good use, adding a zippered chest pocket and sweat-wicking support to get you through your daily schedule. Sustainable Materials",
    sport: "",
    fit: "Standard fit: easy and traditional",
    collection: "",
    salePrice: null,
    image: "/M+NK+DF+24.7+PS+SS+BUTTON+DOWN.webp",
    colors: 5,
    isNew: true,
  },
  {
    id: 2,
    name: "Nike Sportswear",
    category: "Men's T-Shirt",
    price: 35,
    description:
      "Nothing hits like a classic tee. This one is relaxed through the body for easy layering. Its lightweight cotton feels soft and comfortable for everyday wear.",
    sport: "",
    fit: "Standard fit: easy and traditional",
    collection: "",
    salePrice: null,
    image: "/M+NSW+TEE+CLUB+SSNL+WASH+SU25.webp",
    colors: 3,
    isNew: false,
  },
  {
    id: 3,
    name: "Nike ACG 'Lungs'",
    category: "Men's Long-Sleeve T-Shirt",
    price: 55,
    description:
      "This soft, spacious long-sleeve tee has the slightly baggy feel of a vintage tee. To help you out when the views take your breath away, we've printed an extra set of lungs on the chest.",
    sport: "",
    fit: "Loose fit: roomy and relaxed",
    collection: "",
    salePrice: null,
    image: "/M+NRG+ACG+LS+LBR+TEE+LUNGS.avif",
    colors: 3,
    isNew: false,
  },
  {
    id: 4,
    name: "Nike Miler",
    category: "Men's Dri-FIT Running Tank",
    price: 35,
    description:
      "Get those extra miles in with a shirt that won't hold you up. Our sweat-wicking Miler Tank returns with a longer body and ultra-lightweight fabric, so you get more coverage without the weight. It's cool and breathable, with a relaxed fit that won't slow you down.",
    sport: "",
    fit: "Standard fit: easy and traditional",
    collection: "",
    salePrice: null,
    image: "/M+NK+DF+MILER+TANK.avif",
    colors: 3,
    isNew: false,
  },
  {
    id: 5,
    name: "NikeCourt Dri-FIT",
    category: "Men's Tennis Blade Polo",
    price: 40,
    description:
      "Made from sweat-wicking knit fabric that's made from 100% recycled polyester fibers, the NikeCourt Dri-FIT Polo is designed to help you stay dry and comfortable on the court. Its sleek blade collar lies smoothly against your neck for reduced distractions.",
    sport: "Tennis",
    fit: "Standard fit: easy and traditional",
    collection: "",
    salePrice: null,
    image: "/M+NKCT+DF+POLO+BLADE+SOLID.avif",
    colors: 3,
    isNew: false,
  },
  {
    id: 6,
    name: "Kobe",
    category: "Men's Basketball T-Shirt",
    price: 40,
    description:
      "Embody Mamba Mentality with this classic-fit tee. It's built with soft midweight cotton and features his signature Sheath logo.",
    sport: "Basketball",
    fit: "Loose fit: roomy and relaxed",
    collection: "",
    salePrice: null,
    image: "/KB+U+NK+TEE+BETTERMENTAL.avif",
    colors: 3,
    isNew: true,
  },
  {
    id: 7,
    name: "Nike Pro",
    category: "Men's Dri-FIT Slim Long-Sleeve Fitness Top",
    price: 27,
    description:
      "The Nike Pro collection means feeling confident in whatever stage of your workout journey you find yourself. This slim-fitting long-sleeve top has a smooth and stretchy feel for the sports and activities that you love.",
    sport: "Football",
    fit: "Slim fit: sleek and tailored",
    collection: "",
    salePrice: null,
    image: "/M+NP+DF+SLIM+TOP+LS.avif",
    colors: 3,
    isNew: false,
  },
  {
    id: 8,
    name: "Nike Sportswear",
    category: "Max90 T-Shirt",
    price: 45,
    description:
      "Max90 tees have a loose fit with dropped shoulders, longer sleeves and a roomy feel through the body and hips for a casual look. Midweight cotton feels soft and slightly structured for durable, daily comfort.",
    sport: "",
    fit: "Loose fit: roomy and relaxed",
    collection: "",
    salePrice: null,
    image: "/U+NSW+TEE+M90+OC+FESTIVAL+AOP.avif",
    colors: 3,
    isNew: false,
  },
  {
    id: 9,
    name: "Nike Dri-FIT Miler",
    category: "Men's Running T-Shirt",
    price: 35,
    salePrice: null,
    image: "/placeholder.svg?height=400&width=400",
    colors: 3,
    isNew: true,
  },
  {
    id: 10,
    name: "Nike Dri-FIT ADV TechKnit Ultra",
    category: "Men's Running T-Shirt",
    price: 75,
    salePrice: 55,
    image: "/placeholder.svg?height=400&width=400",
    colors: 1,
    isNew: false,
  },
  {
    id: 11,
    name: "Nike Dri-FIT Team",
    category: "Men's Basketball T-Shirt",
    price: 35,
    salePrice: null,
    image: "/placeholder.svg?height=400&width=400",
    colors: 4,
    isNew: false,
  },
  {
    id: 12,
    name: "Nike Sportswear Premium Essentials",
    category: "Men's T-Shirt",
    price: 40,
    salePrice: null,
    image: "/placeholder.svg?height=400&width=400",
    colors: 2,
    isNew: true,
  },
];
